server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://nora-db-1.ciur6yill7ql.ap-northeast-2.rds.amazonaws.com/nora
    username: admin
    password: errordontknow
    driver-class-name: com.mysql.cj.jdbc.Driver